@startuml
title ページ遷移図

threadPage : スレッドページ
insert : POST 投稿
delete : GET 削除確認\nPOST 削除

[*] -> threadPage
threadPage --> threadPage:リンク\nname\ntext\ntime
insert --> threadPage

threadPage --> delete:リンク\ntid
delete --> threadPage

@enduml