@startuml
title 削除

actor ユーザー

ユーザー -> threadPage : 削除ボタン
threadPage -> ThreadDeleteServlet : GET
ThreadDeleteServlet -> threadDelete.jsp : フォワード
ThreadDeleteServlet -> ユーザー : 確認画面
ユーザー -> ThreadDeleteServlet : 確認ボタン
threadDelete.jsp -> ThreadDeleteServlet : POST
ThreadDeleteServlet -> ThreadDAO : New()
ThreadDeleteServlet -> ThreadDAO : delete()
ThreadDeleteServlet -> threadPage : 遷移
threadPage -> ユーザー : 表示

@enduml