@startuml
title 閲覧、追加

actor ユーザー

ユーザー -> threadPage : フォーム、追加ボタン
threadPage -> threadServlet : スレッド
threadServlet -> thread : 生成
thread -> threadServlet : スレッド追加
threadServlet -> threadPage : 遷移
threadPage -> ユーザー : 表示

@enduml